import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from '../../../core/auth/services/auth.service';

@Component({
  selector: 'app-admin-layout', changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, RouterLinkActive, RouterOutlet],
  template: `<div class="admin-shell"><aside [class.open]="menuOpen()"><div class="brand"><span class="brand-mark">M</span><div><strong>Meridian</strong><small>Admin console</small></div></div><nav aria-label="Admin navigation">@for(item of navigation;track item.path){<a [routerLink]="item.path" routerLinkActive="active" [routerLinkActiveOptions]="{exact:item.exact}" (click)="menuOpen.set(false)"><span class="nav-icon">{{item.icon}}</span>{{item.label}}</a>}</nav><div class="sidebar-footer"><a routerLink="/">View website</a><button type="button" (click)="auth.logout()">Sign out</button></div></aside>@if(menuOpen()){<button class="scrim" aria-label="Close menu" (click)="menuOpen.set(false)"></button>}<main><header><button class="menu-button" type="button" aria-label="Open menu" (click)="menuOpen.set(true)">☰</button><div><p>Administration</p><strong>{{auth.currentUser()?.displayName}}</strong></div><span class="avatar">{{initials()}}</span></header><div class="content"><router-outlet /></div></main></div>`,
  styles: `:host{display:block;min-height:100vh;background:#f5f6f8;color:var(--color-text-primary)}.admin-shell{display:grid;grid-template-columns:260px minmax(0,1fr);min-height:100vh}aside{position:sticky;top:0;height:100vh;background:#172233;color:#fff;padding:24px 16px;display:flex;flex-direction:column;z-index:201;box-sizing:border-box}.brand{display:flex;align-items:center;gap:12px;padding:0 8px 25px;border-bottom:1px solid #ffffff1a}.brand-mark{display:grid;place-items:center;width:38px;height:38px;background:var(--color-amber-500);color:#172233;border-radius:8px;font-weight:800}.brand strong,.brand small{display:block}.brand small{color:#9eacbd;font-size:12px;margin-top:2px}nav{display:flex;flex-direction:column;gap:4px;margin-top:20px;overflow:auto}nav a{display:flex;align-items:center;gap:12px;color:#c5cfdb;text-decoration:none;padding:11px 12px;border-radius:7px;font-size:14px;font-weight:600}nav a:hover,nav a.active{color:#fff;background:#ffffff14}.nav-icon{width:20px;text-align:center}.sidebar-footer{margin-top:auto;display:grid;gap:6px;border-top:1px solid #ffffff1a;padding-top:16px}.sidebar-footer a,.sidebar-footer button{padding:10px 12px;background:none;border:0;text-align:left;color:#c5cfdb;text-decoration:none;font:inherit;cursor:pointer}main{min-width:0}header{height:72px;background:#fff;border-bottom:1px solid var(--color-border);padding:0 30px;display:flex;align-items:center;justify-content:flex-end;gap:14px;position:sticky;top:0;z-index:100}header p{margin:0;color:var(--color-text-muted);font-size:12px;text-align:right}header strong{font-size:14px}.avatar{display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:var(--color-teal-100);color:var(--color-teal-600);font-weight:800}.content{padding:32px;max-width:1500px;margin:auto}.menu-button,.scrim{display:none}@media(max-width:850px){.admin-shell{display:block}aside{position:fixed;left:0;transform:translateX(-100%);transition:transform .2s ease;width:260px}aside.open{transform:none}.scrim{display:block;position:fixed;inset:0;background:#10192788;border:0;z-index:200}.menu-button{display:block;border:0;background:none;font-size:24px;margin-right:auto}header{padding:0 18px}.content{padding:22px 16px}}`,
})
export class AdminLayoutComponent {
  protected readonly auth=inject(AuthService); protected readonly menuOpen=signal(false);
  protected readonly navigation=[{path:'/admin',label:'Overview',icon:'⌂',exact:true},{path:'/admin/users',label:'Users',icon:'◎',exact:false},{path:'/admin/reservations',label:'Reservations',icon:'▣',exact:false},{path:'/admin/hotels',label:'Hotels',icon:'▤',exact:false},{path:'/admin/voyages',label:'Voyages',icon:'✈',exact:false},{path:'/admin/circuits',label:'Circuits',icon:'◇',exact:false},{path:'/admin/agencies',label:'B2B agencies',icon:'▦',exact:false},{path:'/admin/reporting',label:'Reporting',icon:'↗',exact:false},{path:'/admin/configuration',label:'Settings',icon:'⚙',exact:false}];
  protected initials():string{return this.auth.currentUser()?.displayName.split(' ').map(v=>v[0]).join('').slice(0,2).toUpperCase()??'AD'}
}
